# Use the ubi9 Node.js minimal image from registry.redhat.io
FROM registry.access.redhat.com/ubi9/nodejs-20-minimal AS builder

# Set the working directory inside the container
WORKDIR /app

# Copy package.json and package-lock.json into the container
COPY --chown=1001:1001 package*.json .

# Install dependencies
RUN npm ci

# Copy files to container with updated permissions
COPY --chown=1001:1001 . ./

# Build
RUN npm run build

# Nginx container
FROM registry.access.redhat.com/ubi9/ubi-minimal

# Install NGINX
RUN microdnf -y upgrade && \
    microdnf -y install nginx && \
    microdnf clean all

# Copy build files from builder stage
COPY --from=builder /app/out /usr/share/nginx/html
COPY .docker/nginx.conf /etc/nginx/nginx.conf

# Link nginx logs to stderr and stdout
RUN ln -sf /dev/stdout /var/log/nginx/access.log \
    && ln -sf /dev/stderr /var/log/nginx/error.log

# Expose port
EXPOSE 8080

CMD ["nginx", "-g", "daemon off;"]