apiVersion: v1
kind: Service
metadata:
  name: gng-whisper
  labels:
    app.kubernetes.io/name: gng-whisper
    app.kubernetes.io/component: whisper
    app.kubernetes.io/part-of: gng-platform
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 9000
      targetPort: http
      protocol: TCP
  selector:
    app.kubernetes.io/name: gng-whisper
