apiVersion: v1
kind: Service
metadata:
  name: gng-web
  labels:
    app.kubernetes.io/name: gng-web
    app.kubernetes.io/component: web
    app.kubernetes.io/part-of: gng-platform
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 3000
      targetPort: http
      protocol: TCP
  selector:
    app.kubernetes.io/name: gng-web
